spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/qozzbank
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    root: INFO
    io.qozz.qozzbank: INFO # Поправил пакет на твой io.qozz
    org.hibernate.SQL: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%25.25thread] %logger{36}: %msg%n"